server:
  port: ${PORT:8080}  # Render define PORT, si no está usa 8080 local

# API Configuration
api:
  version: v1
  version-path: /api/v1

spring:
  application:
    name: crypto-middleware
  jta:
    atomikos:
      datasource:
        default-jta: true
        max-pool-size: 10
        min-pool-size: 3
      connectionfactory:
        max-pool-size: 10
        min-pool-size: 3
  cloud:
    gateway:
      routes:
        - id: crypto-service
          uri: lb://crypto-service
          predicates:
            - Path=/api/v1/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20